### ISSUE TITLE
How --resize works if I set --maintain_aspect_ratio

### ISSUE THREAD

**Issue by jrichardsz** [DarshanDeshpande/tfrecord-generator#1]
If my images has this dimension: 800 x 600 and I use 

```
--resize 500,500 \
--maintain_aspect_ratio \
```

How it works? On my experience with some photo editors, if I  increase/decrease to a new dimension keeping the aspect radio I can't assign a final width/height.

Thanks for your invaluable contribution.

Regards

**Comment by DarshanDeshpande** [comment]
Yes. They are independent. If you decide to maintain the aspect ratio then it will only match one dimension (height) and make the other dimension (width) flexible. The script uses Tensorflow's `tf.image.resize` function so you can refer to TF's documentation for more information regarding resizing.

I hope this solves your query. If not, feel free to continue this thread.
